### ISSUE TITLE
youtube.py", line 284, in upload     hint=await page.locator('#error-short style-scope ytcp-uploads-dialog').text_content()

### ISSUE THREAD

**Issue by skygui** [wanghaisheng/youtube-auto-upload#28]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/wanghaisheng/youtube-auto-upload#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/wanghaisheng/youtube-auto-upload/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/wanghaisheng/youtube-auto-upload/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

youtube.py", line 284, in upload
    hint=await page.locator('#error-short style-scope ytcp-uploads-dialog').text_content()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#error-short style-scope ytcp-uploads-dialog"

System:
OS: 
ubuntu 18.04,
windows 10

=========================== ===========================

usr/lib/python3.7/asyncio/unix_events.py:878: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
  RuntimeWarning)
Traceback (most recent call last):
  File "onefile.py", line 153, in <module>
    scheduletopublish_7dayslater()
  File "onefile.py", line 145, in scheduletopublish_7dayslater
    publish_date=publish_date
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/mnt/emaker/utils/youtube_auto/ytb_up/youtube.py", line 284, in upload
    hint=await page.locator('#error-short style-scope ytcp-uploads-dialog').text_content()
  File "/home/skygui/.local/lib/python3.7/site-packages/playwright/async_api/_generated.py", line 13592, in text_content
    await self._impl_obj.text_content(timeout=timeout)
  File "/home/skygui/.local/lib/python3.7/site-packages/playwright/_impl/_locator.py", line 471, in text_content
    **params,
  File "/home/skygui/.local/lib/python3.7/site-packages/playwright/_impl/_frame.py", line 534, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "/home/skygui/.local/lib/python3.7/site-packages/playwright/_impl/_connection.py", line 44, in send
    lambda: self.inner_send(method, params, False)
  File "/home/skygui/.local/lib/python3.7/site-packages/playwright/_impl/_connection.py", line 387, in wrap_api_call
    return await cb()
  File "/home/skygui/.local/lib/python3.7/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#error-short style-scope ytcp-uploads-dialog"
============================================================

**Comment by cxl0704** [comment]
Replace with the following statement:
```python
hint=await page.locator('div.error-short.style-scope.ytcp-uploads-dialog').text_content()
```
