### ISSUE TITLE
Error: waiting for selector "[class="progress-label style-scope ytcp-video-upload-progress"]"

### ISSUE THREAD

**Issue by n1Ls5** [wanghaisheng/youtube-auto-upload#9]
Environment: Windows 10
Issue frequency: Not frequent.
Error Details:

clear existing tags
filling new  tags
Traceback (most recent call last):
  File "C:\nft\youtube-auto-upload-playwright\upload.py", line 39, in <module>
    was_uploaded, upload_video_id = upload.upload(
  File "C:\nft\youtube-auto-upload-playwright\ytb_up\upload.py", line 316, in upload
    wait_for_processing(page,process=False)
  File "C:\nft\youtube-auto-upload-playwright\ytb_up\utils.py", line 95, in wait_for_processing
    '[class="progress-label style-scope ytcp-video-upload-progress"]').text_content()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 13452, in text_content
    self._sync(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 455, in text_content
    return await self._frame.text_content(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 517, in text_content
    return await self._channel.send("textContent", locals_to_params(locals()))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Error: strict mode violation: "[class="progress-label style-scope ytcp-video-upload-progress"]" resolved to 2 elements:
    1) <span class="progress-label style-scope ytcp-video-upl…>Checking 0%</span> aka playwright.$("#video-result-0 >> text=Checking 0%")
    2) <span class="progress-label style-scope ytcp-video-upl…>Checking 0% ... 5 minutes left</span> aka playwright.$("text=Checking 0% ... 5 minutes left")

=========================== logs ===========================
waiting for selector "[class="progress-label style-scope ytcp-video-upload-progress"]"
  Error: strict mode violation: "[class="progress-label style-scope ytcp-video-upload-progress"]" resolved to 2 elements:
    1) <span class="progress-label style-scope ytcp-video-upl…>Checking 0%</span> aka playwright.$("#video-result-0 >> text=Checking 0%")
    2) <span class="progress-label style-scope ytcp-video-upl…>Checking 0% ... 5 minutes left</span> aka playwright.$("text=Checking 0% ... 5 minutes left")

============================================================
PS C:\nft\youtube-auto-upload-playwright\video> node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at PipeTransport.send (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\playwright\driver\package\lib\protocol\transport.js:54:21)
    at DispatcherConnection.dispatcherConnection.onmessage (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\playwright\driver\package\lib\cli\driver.js:63:57)
    at DispatcherConnection.sendMessageToClient (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\dispatcher.js:187:10)
    at BrowserContextDispatcher._dispatchEvent (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\dispatcher.js:108:22)
    at FFBrowserContext.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\browserContextDispatcher.js:114:19)
    at FFBrowserContext.emit (node:events:390:28)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}

**Comment by nilesh1995** [comment]
@wanghaisheng Can you please help me with this

**Comment by wanghaisheng** [comment]
dm me 
whs860603@gmail.com

**Comment by nilesh1995** [comment]
@wanghaisheng I have emailed you. Please check
